const mockPayload = {
  fn_index: 162,
  data: [
    'task(787zizrft2j2clw)',
    0,
    'make me look handsome ',
    '',
    [],
    'data....',
    null,
    null,
    null,
    null,
    null,
    null,
    20,
    'Euler a',
    4,
    0,
    'original',
    false,
    false,
    1,
    1,
    30,
    1.5,
    0.75,
    -1, // seed
    -1,
    0,
    0,
    0,
    false,
    null,
    512,
    512,
    1,
    'Just resize',
    'Whole picture',
    32,
    'Inpaint masked',
    '',
    '',
    '',
    [],
    'None',
    '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n',
    true,
    true,
    '',
    '',
    true,
    50,
    true,
    1,
    0,
    false,
    4,
    0.5,
    'Linear',
    'None',
    '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>',
    128,
    8,
    ['left', 'right', 'up', 'down'],
    1,
    0.05,
    128,
    4,
    'fill',
    ['left', 'right', 'up', 'down'],
    false,
    false,
    'positive',
    'comma',
    0,
    false,
    false,
    '',
    '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>',
    64,
    'None',
    2,
    'Seed',
    '',
    [],
    'Nothing',
    '',
    [],
    'Nothing',
    '',
    [],
    true,
    false,
    false,
    false,
    0,
    [
      {
        name: '/Users/skob/Work/AI/stable-diffusion-webui/outputs/img2img-images/2023-05-23/00016-1622638337.png',
        data: 'http://127.0.0.1:7860/file=/Users/skob/Work/AI/stable-diffusion-webui/outputs/img2img-images/2023-05-23/00016-1622638337.png',
        is_file: true,
      },
    ],
    '{"prompt": "make me look handsome ", "all_prompts": ["make me look handsome "], "negative_prompt": "", "all_negative_prompts": [""], "seed": 1622638337, "all_seeds": [1622638337], "subseed": 702183994, "all_subseeds": [702183994], "subseed_strength": 0, "width": 512, "height": 512, "sampler_name": "Euler a", "cfg_scale": 30, "steps": 20, "batch_size": 1, "restore_faces": false, "face_restoration_model": null, "sd_model_hash": "cc6cb27103", "seed_resize_from_w": 0, "seed_resize_from_h": 0, "denoising_strength": 0.75, "extra_generation_params": {}, "index_of_first_image": 0, "infotexts": ["make me look handsome \\nSteps: 20, Sampler: Euler a, CFG scale: 30, Seed: 1622638337, Size: 512x512, Model hash: cc6cb27103, Model: v1-5-pruned-emaonly, Denoising strength: 0.75"], "styles": [], "job_timestamp": "20230523181603", "clip_skip": 1, "is_using_inpainting_conditioning": false}',
    '<p>make me look handsome <br>\nSteps: 20, Sampler: Euler a, CFG scale: 30, Seed: 1622638337, Size: 512x512, Model hash: cc6cb27103, Model: v1-5-pruned-emaonly, Denoising strength: 0.75</p>',
    "<p></p><div class='performance'><p class='time'>Time taken: <wbr>18.33s</p></div>",
  ],
  event_data: null,
  session_hash: '0duke98utwr',
}
export { mockPayload }
