const emotions = [
  'Joy',
  'Trust',
  'Surprise',
  'Love',
  'Optimism',
  'Surprise',
  'Curiosity',
  'Desire',
  'Pride',
]

const styles = [
  //   'Cubism',
  //   'Impressionism',
  //   'Modernism',
  //   'Neoclassicism',
  //   'Pop Art',
  //   'Rococo',
  'Photorealism',
  //   'Constructivism',
  //   'Post-Modernism',
]
let transitionPercent = 5
let style = 'Neo-pop'
let emotion = 'Joy'

const generatePrompts = (frames) => {
  let prompts = []
  for (let i = 0; i < frames; i++) {
    const randomEmotion = emotions[Math.floor(Math.random() * emotions.length)]
    const randomStyle = styles[Math.floor(Math.random() * styles.length)]
    if (transitionPercent <= 25) {
      style = randomStyle
      emotion = randomEmotion
    }
    prompts.push(
      `A cat face with ${emotion} in the style of ${transitionPercent}% of a ${style} in a day time scene.`
    )
    transitionPercent += 20
    if (transitionPercent > 100) {
      transitionPercent = 5
    }
  }
  // return prompts
  return prompts2
}

const newPrompts = [
  'Transform the cat into a tiger using watercolor painting.',
  'Apply a pointillism effect to gradually turn the cat into a tiger.',
  'Give the cat a pop art style, transitioning it into a tiger.',
  'Create a sketch of the cat that gradually becomes a tiger.',
  'Make the cat transition into a tiger with a stained glass artwork effect.',
  'Apply an oil painting effect to transform the cat into a tiger.',
  'Give the cat a vintage sepia tone as it transitions into a tiger.',
  'Gradually pixelate the cat to transform it into a tiger.',
  'Create a charcoal drawing that gradually becomes a tiger from the cat.',
  'Make the cat transition into a tiger with a graffiti art style.',
  'Apply a cubist style to the cat, gradually transforming it into a tiger.',
  'Give the cat a mosaic effect as it transitions into a tiger.',
  'Create a surrealist masterpiece that gradually becomes a tiger from the cat.',
  'Transform the cat into a tiger by gradually turning it into a silhouette.',
  'Make the cat transition into a tiger with a comic book illustration style.',
  'Apply a neon glow effect to gradually transform the cat into a tiger.',
  'Give the cat a minimalistic art style as it transitions into a tiger.',
  'Create a mixed media artwork that gradually transforms the cat into a tiger.',
  'Make the cat transition into a tiger with a woodcut print effect.',
  'Apply a point perspective drawing style to gradually turn the cat into a tiger.',
  'Give the cat a fauvism style as it transitions into a tiger.',
  'Transform the cat into a tiger with a futuristic digital art look.',
  'Gradually transition the cat into a tiger by turning it into a collage.',
  'Create a pastel painting that gradually becomes a tiger from the cat.',
  'Make the cat transition into a tiger with a tapestry artwork effect.',
  'Apply a surrealistic pop art effect to transform the cat into a tiger.',
  'Give the cat a glitch art style as it transitions into a tiger.',
  'Transform the cat into a tiger with a linocut print effect.',
  'Gradually transition the cat into a tiger by creating a caricature.',
  'Make the cat transition into a tiger with a watercolor ink wash effect.',
  'Apply a modern abstract art style to gradually transform the cat into a tiger.',
  'Give the cat a stained paper texture as it transitions into a tiger.',
  'Transform the cat into a 3D rendered artwork that gradually becomes a tiger.',
  'Gradually transition the cat into a tiger by creating a digital painting.',
  'Make the cat transition into a tiger with a street art mural effect.',
  'Apply a realism effect to transform the cat into a tiger.',
  'Give the cat a vintage poster look as it transitions into a tiger.',
  'Transform the cat into a paper cutout art piece that gradually becomes a tiger.',
  'Gradually transition the cat into a tiger by creating a monochromatic painting.',
  'Make the cat transition into a tiger with a contemporary art installation style.',
  'Apply a watercolor splatter effect to gradually transform the cat into a tiger.',
  'Give the cat a futuristic cyberpunk style as it transitions into a tiger.',
  'Transform the cat into a textile pattern that gradually becomes a tiger.',
  'Gradually transition the cat into a tiger by creating a stained glass mosaic.',
  'Make the cat transition into a tiger with a digital glitch artwork effect.',
  'Apply an impressionism style to gradually transform the cat into a tiger.',
  'Give the cat a retro comic book effect as it transitions into a tiger.',
  'Transform the cat into a clay sculpture that gradually becomes a tiger.',
  'Gradually transition the cat into a tiger by creating a light painting.',
  'Make the cat transition into a tiger with a mixed media collage effect.',
  'Apply a post-impressionism style to gradually transform the cat into a tiger.',
  'Give the cat a vintage film photography look as it transitions into a tiger.',
  'Transform the cat into a spray paint graffiti that gradually becomes a tiger.',
  'Gradually transition the cat into a tiger by creating a portrait painting.',
  'Make the cat transition into a tiger with a scratchboard drawing effect.',
  'Apply a street art style to gradually transform the cat into a tiger.',
  'Give the cat a futuristic holographic look as it transitions into a tiger.',
  'Transform the cat into a digital mosaic that gradually becomes a tiger.',
  'Gradually transition the cat into a tiger by creating a cubist portrait.',
  'Make the cat transition into a tiger with a charcoal sketch effect.',
  'Apply a minimalist geometric art style to gradually transform the cat into a tiger.',
  // ... rest of the prompts for the remaining steps
]

const prompts2 = [
  'Create a watercolor painting.',
  'Apply a pointillism effect.',
  'Give it a pop art style.',
  'Create a sketch.',
  'Make it look like a stained glass artwork.',
  'Apply an oil painting effect.',
  'Give it a vintage sepia tone.',
  'Transform it into a pixelated art piece.',
  'Create a charcoal drawing.',
  'Make it look like a graffiti artwork.',
  'Apply a cubist style.',
  'Give it a mosaic effect.',
  'Create a surrealist masterpiece.',
  'Transform it into a silhouette.',
  'Make it look like a comic book illustration.',
  'Apply a neon glow effect.',
  'Give it a minimalistic art style.',
  'Create a mixed media artwork.',
  'Make it look like a woodcut print.',
  'Apply a point perspective drawing style.',
  'Give it a fauvism style.',
  'Create a futuristic digital art look.',
  'Transform it into a collage.',
  'Make it look like a pastel painting.',
  'Apply a tapestry artwork effect.',
  'Give it a surrealistic pop art effect.',
  'Create a glitch art style.',
  'Transform it into a linocut print.',
  'Make it into a caricature.',
  'Apply a watercolor ink wash effect.',
  'Give it a modern abstract art style.',
  'Create a stained paper texture.',
  'Transform it into a 3D rendered artwork.',
  'Make it a digital painting.',
  'Apply a street art mural effect.',
  'Give it a realism effect.',
  'Create a vintage poster look.',
  'Transform it into a paper cutout art piece.',
  'Make it a monochromatic painting.',
  'Apply a contemporary art installation style.',
  'Give it a watercolor splatter effect.',
  'Create a futuristic cyberpunk style.',
  'Transform it into a textile pattern.',
  'Make it a stained glass mosaic.',
  'Apply an impressionism style.',
  'Give it a retro comic book effect.',
  'Create a clay sculpture.',
  'Make it a light painting.',
  'Apply a mixed media collage effect.',
  'Give it a post-impressionism style.',
  'Create a vintage film photography look.',
  'Transform it into a spray paint graffiti.',
  'Make it a portrait painting.',
  'Apply a scratchboard drawing effect.',
  'Give it a street art style.',
  'Create a futuristic holographic look.',
  'Transform it into a digital mosaic.',
  'Make it a cubist portrait.',
  'Apply a charcoal sketch effect.',
  'Give it a minimalist geometric art style.',
  'Apply an abstract expressionism style.',
  'Create a reverse perspective drawing.',
  'Transform it into a realistic sculpture.',
  'Make it a mixed media installation.',
  'Give it a vibrant neon color scheme.',
  'Create a futuristic sci-fi illustration.',
  'Apply a motion blur effect.',
  'Transform it into a geometric pattern.',
  'Make it a minimalist line art.',
  'Give it a dreamy ethereal effect.',
  'Create a textured impasto painting.',
  'Apply a fractal art style.',
  'Transform it into a minimalist silhouette.',
  'Make it an abstract light photography.',
  'Give it a glitchy digital distortion effect.',
  'Create a kaleidoscopic design.',
  'Apply a low poly 3D modeling effect.',
  'Transform it into an origami sculpture.',
  'Make it a surreal floating composition.',
  'Give it a vintage photo filter effect.',
  'Create a reflective mirror art piece.',
  'Apply a holographic foil texture.',
  'Transform it into a vibrant stained glass window.',
  'Make it an abstract kinetic sculpture.',
  'Give it a water ripple distortion effect.',
  'Create an isometric illustration.',
  'Apply a cubism-inspired photomontage effect.',
  'Transform it into an ASCII art representation.',
  'Make it a double exposure composition.',
  'Give it a glitchy VHS tape effect.',
  'Create a fractal-based generative artwork.',
  'Apply a wireframe 3D rendering effect.',
  'Transform it into a minimalist typography design.',
  'Make it a surreal levitation photograph.',
  'Give it a glitch art style with pixel sorting.',
  'Create an abstract fluid painting.',
  'Apply a digital glitch distortion effect.',
  'Transform it into a realistic charcoal portrait.',
  'Make it a futuristic cybernetic illustration.',
  'Give it a vintage collage aesthetic.',
  'Create a vibrant neon light installation.',
  'Apply a surreal double exposure effect.',
  'Transform it into a mosaic tile pattern.',
  'Make it an abstract kinetic light sculpture.',
  'Give it a pixel art retro game style.',
  'Create an impressionistic landscape painting.',
  'Apply a low poly origami paper effect.',
  'Transform it into a mixed media photo collage.',
  'Make it a minimalist black and white photograph.',
  'Give it a glitch typography design.',
  'Create a geometric abstract sculpture.',
  'Apply a surreal infrared photography effect.',
  'Transform it into an abstract digital fractal.',
  'Make it a retro futuristic illustration.',
  'Give it a neon graffiti street art style.',
  'Create a realistic oil portrait.',
  'Apply a pointillism-inspired digital artwork effect.',
  'Transform it into a paper quilling art piece.',
  'Make it a minimalist architectural drawing.',
  'Give it a surreal floating island composition.',
  'Create an abstract glitchy video animation.',
  'Apply a stained glass effect with vibrant colors.',
  'Transform it into an abstract expressionist painting.',
  'Make it a futuristic cityscape illustration.',
  'Give it a retro comic book halftone effect.',
  'Create a realistic still life drawing.',
  'Apply a collage-style mixed media composition.',
  'Transform it into an abstract liquid art piece.',
  'Make it a pixel art isometric game scene.',
  'Give it a dreamy double exposure photography effect.',
  'Create a geometric tessellation pattern.',
  'Apply a digital painting technique.',
  'Transform it into a wire sculpture.',
  'Make it an abstract neon light photography.',
  'Give it a glitch art style with data bending.',
  'Create a surreal nature-inspired artwork.',
  'Apply a vaporwave color palette and aesthetic.',
  'Transform it into a minimalist paper folding sculpture.',
  'Make it a contemporary abstract painting.',
  'Give it a vintage polaroid photo effect.',
  'Create a light installation with interactive elements.',
  'Apply a fragmented and shattered glass effect.',
  'Transform it into an abstract geometric typography.',
  'Make it a surreal underwater photography.',
  'Give it a glitch art style with datamoshing.',
  'Create a realistic wildlife portrait.',
  'Apply a cubism-inspired architectural illustration.',
  'Transform it into a mosaic ceramic art piece.',
  'Make it a minimalist vector icon design.',
  'Give it a cosmic and celestial theme.',
  'Create an abstract kinetic sculpture with moving parts.',
  'Apply a fragmented collage technique.',
  'Transform it into a retro pixel art animation.',
  'Make it a dreamy long exposure night photograph.',
  'Give it a glitchy circuit board aesthetic.',
  'Create a surreal fantasy landscape painting.',
  'Apply a charcoal sketch effect with cross-hatching.',
  'Transform it into a wireframe architectural visualization.',
  'Make it an abstract light and shadow play.',
  'Give it a glitch art style with circuit bending.',
  'Create a hyperrealistic still life painting.',
  'Apply a photorealistic digital painting technique.',
  'Transform it into a folded paper origami animal.',
  'Make it a minimalist monochromatic illustration.',
  'Give it a surreal floating city composition.',
  'Create a glitchy audiovisual art installation.',
  'Apply a mosaic pixelation effect.',
  'Transform it into an abstract geometric pattern.',
  'Make it a futuristic robot concept design.',
  'Give it a vintage film noir aesthetic.',
  'Create a kinetic wind sculpture.',
  'Apply a fragmented mirror reflection effect.',
  'Transform it into a mixed media assemblage art piece.',
  'Make it an abstract ink in water photography.',
  'Give it a glitch art style with code manipulation.',
  'Create a realistic portrait in watercolor.',
  'Apply a surrealist photomanipulation effect.',
  'Transform it into a minimalist line art tattoo design.',
  'Make it a conceptual architectural blueprint.',
  'Give it a surreal floating object composition.',
  'Create a glitchy video mapping projection.',
  'Apply a neon light trail long exposure effect.',
  'Transform it into a pixel art character sprite.',
  'Make it an abstract smoke and fog painting.',
  'Give it a glitch art style with image corruption.',
  'Create a macro photography of natural textures.',
  'Apply a retro futuristic glitch typography effect.',
  'Transform it into a stone sculpture.',
  'Make it a minimalist black and white landscape photograph.',
  'Give it a dreamy ethereal double exposure effect.',
  'Create a 3D printed sculpture with intricate details.',
  'Apply a fractured glass mosaic effect.',
  'Transform it into an abstract kinetic light installation.',
  'Make it a pixel art platformer game background.',
  'Give it a surreal levitation and floating effect.',
  'Create an abstract digital glitch artwork.',
  'Apply a fragmented glitch typography design.',
  'Transform it into a clay pottery art piece.',
  'Make it a minimalist geometric architecture photograph.',
  'Give it a cosmic and galactic space exploration theme.',
  'Create an interactive kinetic sculpture installation.',
  'Apply a pixel sorting glitch effect.',
  'Transform it into an abstract geometric mosaic.',
  'Make it a futuristic concept vehicle design.',
  'Give it a vintage sepia-toned landscape photograph effect.',
  'Create a light painting photography with movement.',
  'Apply a digital glitch art effect with chromatic aberration.',
  'Transform it into a paper sculpture of a famous landmark.',
  'Make it a minimalist abstract line art drawing.',
  'Give it a surreal floating object composition in a dreamlike setting.',
  'Create an augmented reality (AR) interactive art experience.',
  'Apply a fragmented glitch effect with double exposure.',
  'Transform it into an abstract stained glass window design.',
  'Make it a conceptual futuristic space station illustration.',
  'Give it a vintage retro typography design.',
  'Create a kinetic sculpture with intricate mechanical movements.',
  'Apply a shattered mirror reflection effect.',
  'Transform it into a mixed media collage with found objects.',
  'Make it an abstract macro photography of textures.',
  'Give it a glitch art style with audio-reactive visuals.',
  'Create a realistic still life painting with fruits and flowers.',
  'Apply a surrealist photomontage technique.',
  'Transform it into a wireframe 3D model of an animal.',
  'Make it a minimalist black and white architectural photograph.',
  'Give it a dreamy ethereal misty landscape effect.',
  'Create a light installation with interactive projection mapping.',
  'Apply a fragmented typography design with glitch elements.',
  'Transform it into a paper quilling sculpture of an animal.',
  'Make it a minimalist abstract composition with bold colors.',
  'Give it a surreal floating cityscape composition at sunset.',
  'Create an abstract video art projection with generative visuals.',
  'Apply a fragmented glitch effect with pixel displacement.',
  'Transform it into a wire sculpture of a human figure.',
  'Make it an abstract long exposure photography of city lights.',
  'Give it a glitch art style with abstract algorithmic patterns.',
  'Create a hyperrealistic portrait in graphite pencil.',
  'Apply a photorealistic digital painting technique with depth of field.',
  'Transform it into a folded paper origami flower.',
  'Make it a minimalist black and white portrait photograph.',
  'Give it a surreal floating island composition at sunrise.',
  'Create a glitchy audiovisual performance with live coding.',
  'Apply a mosaic pixelation effect with depth of field.',
  'Transform it into an abstract geometric design with symmetry.',
  'Make it a futuristic concept spaceship design.',
  'Give it a vintage film noir aesthetic with film grain effect.',
  'Create a kinetic wind sculpture with moving parts.',
  'Apply a fragmented mirror reflection effect with shattered glass.',
  'Transform it into a mixed media collage with abstract elements.',
  'Make it an abstract ink in water photography with vibrant colors.',
  'Give it a glitch art style with glitch typography.',
  'Create a realistic wildlife portrait in colored pencils.',
  'Apply a surrealist photomanipulation technique with double exposure.',
  'Transform it into a minimalist line art tattoo design of an animal.',
  'Make it a conceptual architectural blueprint with detailed annotations.',
  'Give it a surreal floating object composition in a dreamy landscape.',
  'Create a glitchy video mapping projection with audio-reactive visuals.',
  'Apply a neon light trail long exposure effect with light painting.',
  'Transform it into a pixel art character sprite for a retro game.',
  'Make it an abstract smoke and fog painting with atmospheric depth.',
  'Give it a glitch art style with image corruption and databending.',
  'Create a macro photography of natural textures with shallow depth of field.',
  'Apply a retro futuristic glitch typography effect with futuristic elements.',
  'Transform it into a stone sculpture with intricate carved details.',
  'Make it a minimalist black and white landscape photograph with strong contrast.',
  'Give it a dreamy ethereal double exposure effect with nature elements.',
  'Create a 3D printed sculpture with complex geometric patterns.',
  'Apply a fractured glass mosaic effect with vibrant colors.',
  'Transform it into an abstract kinetic light installation with interactive elements.',
  'Make it a pixel art platformer game background with parallax scrolling.',
  'Give it a surreal levitation and floating effect in a surrealistic setting.',
  'Create an abstract digital glitch artwork with dynamic visual distortions.',
  'Apply a fragmented glitch typography design with glitchy text elements.',
  'Transform it into a clay pottery art piece with intricate textures.',
  'Make it a minimalist geometric architecture photograph with clean lines.',
  'Give it a cosmic and galactic space exploration theme with celestial elements.',
  'Create an interactive kinetic sculpture installation with motion sensors.',
  'Apply a pixel sorting glitch effect with pixel displacement and color manipulation.',
  'Transform it into an abstract geometric mosaic with tessellations and patterns.',
  'Make it a futuristic concept vehicle design with sleek lines and aerodynamic form.',
  'Give it a vintage sepia-toned landscape photograph effect with vignette and scratches.',
  'Create a light painting photography with light trails and long exposure techniques.',
  'Apply a digital glitch art effect with chromatic aberration and pixelation.',
  'Transform it into a paper sculpture of a famous landmark with intricate details.',
  'Make it a minimalist abstract line art drawing with simplicity and minimal strokes.',
  'Give it a surreal floating object composition in a dreamlike setting with ethereal colors.',
  'Create an augmented reality (AR) interactive art experience with virtual elements.',
  'Apply a fragmented glitch effect with double exposure and abstract elements.',
  'Transform it into an abstract stained glass window design with vibrant colors and patterns.',
  'Make it a conceptual futuristic space station illustration with futuristic architecture.',
  'Give it a vintage retro typography design with distressed textures and retro fonts.',
  'Create a kinetic sculpture with intricate mechanical movements and interactive elements.',
  'Apply a shattered mirror reflection effect with fragmented and distorted reflections.',
  'Transform it into a mixed media collage with found objects and textured materials.',
  'Make it an abstract macro photography of textures with intricate details and shallow depth of field.',
  'Give it a glitch art style with audio-reactive visuals and glitchy animated elements.',
  'Create a realistic still life painting with fruits and flowers in vibrant colors and realistic textures.',
  'Apply a surrealist photomontage technique with juxtaposition and unexpected combinations of elements.',
  'Transform it into a wireframe 3D model of an animal with wireframe rendering and realistic proportions.',
  'Make it a minimalist black and white architectural photograph with strong lines and clean composition.',
  'Give it a dreamy ethereal misty landscape effect with soft and diffused lighting and atmospheric elements.',
  'Create a light installation with interactive projection mapping and dynamic color transitions.',
  'Apply a fragmented typography design with glitch elements and abstract letterforms.',
  'Transform it into a paper quilling sculpture of an animal with intricately rolled and shaped paper strips.',
  'Make it a minimalist abstract composition with bold colors and geometric shapes.',
  'Give it a surreal floating cityscape composition at sunset with otherworldly architecture and dreamy colors.',
  'Create an abstract video art projection with generative visuals and synchronized soundscapes.',
  'Apply a fragmented glitch effect with pixel displacement and abstract patterns.',
  'Transform it into a wire sculpture of a human figure with intricate bends and interlocking wires.',
  'Make it an abstract long exposure photography of city lights with streaks of vibrant colors and dynamic movement.',
  'Give it a glitch art style with abstract algorithmic patterns and chaotic visual elements.',
  'Create a hyperrealistic portrait in graphite pencil with meticulous attention to detail and lifelike textures.',
  'Apply a photorealistic digital painting technique with depth of field and realistic lighting effects.',
  'Transform it into a folded paper origami flower with precise folds and elegant floral form.',
  'Make it a minimalist black and white portrait photograph with emphasis on facial expressions and tonal contrasts.',
  'Give it a surreal floating island composition at sunrise with mystical and dreamlike atmosphere.',
  'Create a glitchy audiovisual performance with live coding and synchronized glitch visuals and soundscapes.',
  'Apply a mosaic pixelation effect with depth of field and gradual transition of mosaic tiles.',
  'Transform it into an abstract geometric design with symmetry and intricate patterns.',
  'Make it a futuristic concept spaceship design with sleek lines and innovative propulsion systems.',
  'Give it a vintage film noir aesthetic with film grain effect, noir lighting, and gritty atmosphere.',
  'Create a kinetic wind sculpture with moving parts and organic shapes that respond to the wind.',
  'Apply a fragmented mirror reflection effect with shattered glass and distorted reflections.',
  'Transform it into a mixed media collage with abstract elements, textures, and layered compositions.',
  'Make it an abstract ink in water photography with vibrant colors and fluid movement.',
  'Give it a glitch art style with glitch typography, distortion effects, and corrupted digital elements.',
  'Create a realistic wildlife portrait in colored pencils with intricate fur, feathers, or scales.',
  'Apply a surrealist photomanipulation technique with double exposure and unexpected combinations of elements.',
  'Transform it into a minimalist line art tattoo design of an animal with clean lines and minimalist forms.',
  'Make it a conceptual architectural blueprint with detailed annotations and precise measurements.',
  'Give it a surreal floating object composition in a dreamy landscape with surreal lighting and atmospheric elements.',
  'Create a glitchy video mapping projection with abstract visuals and glitchy transitions on architectural structures.',
  'Apply a neon light trail long exposure effect with light painting techniques and vibrant light trails.',
  'Transform it into a pixel art character sprite for a retro game with pixel-perfect details and limited color palette.',
  'Make it an abstract smoke and fog painting with atmospheric depth and soft transitions between colors.',
  'Give it a glitch art style with image corruption, data bending, and distorted visual elements.',
  'Create a macro photography of natural textures with shallow depth of field and intricate details.',
  'Apply a retro futuristic glitch typography effect with futuristic elements and retro-inspired typography.',
  'Transform it into a stone sculpture with intricate carved details and realistic texture representation.',
  'Make it a minimalist black and white landscape photograph with strong contrast and minimalist composition.',
  'Give it a dreamy ethereal double exposure effect with nature elements and soft overlays of textures.',
  'Create a 3D printed sculpture with complex geometric patterns and intricate interlocking pieces.',
  'Apply a fractured glass mosaic effect with vibrant colors and intricate placement of mosaic tiles.',
  'Transform it into an abstract kinetic light installation with interactive elements and dynamic light movements.',
  'Make it a pixel art platformer game background with parallax scrolling and pixel-perfect art style.',
  'Give it a surreal levitation and floating effect in a surrealistic setting with gravity-defying elements.',
  'Create an abstract digital glitch artwork with dynamic visual distortions, glitchy textures, and vibrant colors.',
  'Apply a fragmented glitch typography design with glitchy text elements and fragmented letterforms.',
  'Transform it into a clay pottery art piece with intricate textures and sculptural details.',
  'Make it a minimalist geometric architecture photograph with clean lines and balanced composition.',
  'Give it a cosmic and galactic space exploration theme with celestial elements and cosmic color palettes.',
  'Create an interactive kinetic sculpture installation with motion sensors and responsive movements to human interaction.',
  'Apply a pixel sorting glitch effect with pixel displacement, color manipulation, and glitchy visual transitions.',
  'Transform it into an abstract geometric mosaic with tessellations, patterns, and intricate color arrangements.',
  'Make it a futuristic concept vehicle design with sleek lines, aerodynamic form, and innovative propulsion systems.',
  'Give it a vintage sepia-toned landscape photograph effect with vignette, scratches, and nostalgic aesthetics.',
  'Create a light painting photography with light trails, long exposure techniques, and dynamic light movements.',
  'Apply a digital glitch art effect with chromatic aberration, pixelation, and glitchy visual distortions.',
  'Transform it into a paper sculpture of a famous landmark with intricate details and precise folds.',
  'Make it a minimalist abstract line art drawing with simplicity, minimal strokes, and clean composition.',
  'Give it a surreal floating object composition in a dreamlike setting with ethereal colors and whimsical elements.',
  'Create an augmented reality (AR) interactive art experience with virtual elements and interactive projections.',
  'Apply a fragmented glitch effect with double exposure, abstract patterns, and shattered visual elements.',
  'Transform it into an abstract stained glass window design with vibrant colors, intricate patterns, and light transmission effects.',
  'Make it a conceptual futuristic space station illustration with futuristic architecture and advanced technology concepts.',
  'Give it a vintage retro typography design with distressed textures, retro fonts, and nostalgic aesthetics.',
  'Create a kinetic sculpture with intricate mechanical movements, organic shapes, and dynamic balance.',
  'Apply a shattered mirror reflection effect with fragmented and distorted reflections for an abstract and surreal look.',
  'Transform it into a mixed media collage with found objects, textured materials, and layered compositions.',
  'Make it an abstract macro photography of textures with intricate details, patterns, and unique perspectives.',
  'Give it a glitch art style with audio-reactive visuals, glitchy animated elements, and dynamic glitch effects.',
  'Create a realistic still life painting with fruits and flowers, capturing their textures, colors, and delicate details.',
  'Apply a surrealist photomontage technique with juxtaposition, unexpected combinations, and surreal visual narratives.',
  'Transform it into a wireframe 3D model of an animal, emphasizing the structure, contours, and skeletal forms.',
  'Make it a minimalist black and white architectural photograph, highlighting the architectural elements, symmetry, and clean lines.',
  'Give it a dreamy ethereal misty landscape effect with soft and diffused lighting, foggy atmosphere, and subtle color transitions.',
  'Create a light installation with interactive projection mapping, illuminating spaces and objects with dynamic visuals and light effects.',
  'Apply a fragmented typography design with glitch elements, abstract letterforms, and unconventional arrangements of text.',
  'Transform it into a paper quilling sculpture of an animal, intricately rolling and shaping paper strips to form detailed representations.',
  'Make it a minimalist abstract composition with bold colors, geometric shapes, and a sense of balance and simplicity.',
  'Give it a surreal floating cityscape composition at sunset, incorporating otherworldly architecture, dreamy colors, and magical atmosphere.',
  'Create an abstract video art projection with generative visuals, abstract forms, and ambient soundscapes for an immersive experience.',
  'Apply a fragmented glitch effect with pixel displacement, abstract patterns, and glitchy transitions to create a distorted and dynamic look.',
  'Transform it into a wire sculpture of a human figure, capturing the pose, movement, and grace of the human body with wireframe elements.',
  'Make it an abstract long exposure photography of city lights, capturing the dynamic movement, vibrant colors, and energy of urban life.',
  'Give it a glitch art style with abstract algorithmic patterns, chaotic visual elements, and digital glitches for a visually arresting effect.',
  'Create a hyperrealistic portrait in graphite pencil, capturing the intricate details of facial features, textures, and expressions with precision.',
  'Apply a photorealistic digital painting technique with depth of field, realistic lighting, and meticulous attention to detail for a lifelike representation.',
  'Transform it into a folded paper origami flower, carefully folding and shaping the paper to create a beautiful and delicate floral form.',
  'Make it a minimalist black and white portrait photograph, focusing on capturing the essence of the subject with simplicity and strong visual impact.',
  'Give it a surreal floating island composition at sunrise, combining elements of fantasy, dreaminess, and serenity in a captivating setting.',
  'Create a glitchy audiovisual performance with live coding, glitchy soundscapes, and synchronized glitch visuals for a multisensory experience.',
  'Apply a mosaic pixelation effect with depth of field, gradually transitioning from detailed areas to abstract mosaic patterns for an intriguing look.',
  'Transform it into an abstract geometric design with symmetry, intricate patterns, and harmonious color combinations for a visually captivating result.',
  'Make it a futuristic concept spaceship design, exploring innovative shapes, sleek lines, and advanced technologies for an otherworldly vessel.',
  'Give it a vintage film noir aesthetic with film grain effect, noir lighting, and a sense of mystery and nostalgia reminiscent of classic detective movies.',
  'Create a kinetic wind sculpture with moving parts, capturing the beauty of wind-driven motion and incorporating organic forms in a sculptural design.',
  'Apply a fragmented mirror reflection effect with shattered glass, distorted reflections, and fractured visual elements for a visually striking composition.',
  'Transform it into a mixed media collage with abstract elements, textured materials, and layered compositions, combining different mediums and textures for an eclectic visual experience.',
  'Make it an abstract macro photography of textures, zooming in on the intricate details, patterns, and textures found in natural or everyday objects for a visually captivating result.',
  'Give it a glitch art style with audio-reactive visuals, glitchy animated elements, and dynamic glitch effects that respond to sound or music for a visually and sonically engaging experience.',
  'Create a realistic still life painting with fruits and flowers, capturing their colors, textures, and forms with precision and attention to detail for a visually stunning result.',
  'Apply a surrealist photomontage technique, combining elements from different images to create unexpected and dreamlike compositions that challenge reality and provoke the imagination.',
  'Transform it into a wireframe 3D model of an animal, highlighting its skeletal structure, form, and movement with wireframe rendering for a unique and intriguing representation.',
  'Make it a minimalist black and white architectural photograph, focusing on clean lines, symmetry, and the interplay of light and shadows to showcase the architectural beauty and aesthetics.',
  'Give it a dreamy ethereal misty landscape effect, using soft lighting, foggy atmosphere, and subtle color tones to create a sense of tranquility, mystery, and enchantment in the scene.',
  'Create a light installation with interactive projection mapping, using dynamic visuals, light effects, and interactive elements to transform the space and engage the audience in a multisensory experience.',
  'Apply a fragmented typography design, using glitch elements, abstract letterforms, and unconventional compositions to create visually striking and innovative typography that pushes the boundaries of traditional design.',
  'Transform it into a paper quilling sculpture of an animal, using intricately rolled and shaped paper strips to bring the subject to life with meticulous craftsmanship and attention to detail.',
  'Make it a minimalist abstract composition, using bold colors, geometric shapes, and a balanced composition to create a visually impactful and aesthetically pleasing artwork that evokes a sense of harmony and simplicity.',
  'Give it a surreal floating cityscape composition at sunset, using otherworldly architectural elements, dreamy colors, and imaginative details to create a captivating and fantastical urban landscape that transports the viewer to a different reality.',
  'Create an abstract video art projection, using generative visuals, abstract forms, and ambient soundscapes to create an immersive and mesmerizing audiovisual experience that stimulates the senses and evokes emotions.',
  'Apply a fragmented glitch effect, using pixel displacement, abstract patterns, and glitchy transitions to create a visually distorted and dynamic look that challenges traditional notions of perception and reality.',
  'Transform it into a wire sculpture of a human figure, using wireframe elements to capture the grace, movement, and essence of the human form in a minimalist and abstract representation that explores the interplay of positive and negative space.',
  'Make it an abstract long exposure photography of city lights, using extended exposure times and intentional camera movement to capture the energy, vibrancy, and dynamism of urban environments in a visually striking and evocative way.',
  'Give it a glitch art style, using abstract algorithmic patterns, chaotic visual elements, and digital glitches to create a visually arresting and thought-provoking artwork that challenges traditional notions of aesthetics and composition.',
  'Create a hyperrealistic portrait in graphite pencil, using meticulous attention to detail, shading techniques, and texture rendering to capture the nuances and essence of the subject with lifelike precision and depth.',
  'Apply a photorealistic digital painting technique, using advanced digital tools and techniques to recreate the subject with exceptional realism, attention to detail, and mastery of light and color for a truly lifelike representation.',
  'Transform it into a folded paper origami flower, using precise folds and shaping techniques to create an elegant and delicate floral form that showcases the beauty of paper craftsmanship and the art of origami.',
  'Make it a minimalist black and white portrait photograph, using simplicity, contrast, and careful composition to capture the essence and personality of the subject in a timeless and striking way.',
  'Give it a surreal floating island composition at sunrise, using dreamy colors, ethereal lighting, and imaginative elements to create a captivating and whimsical scene that transports the viewer to a fantasy world of their own imagination.',
  'Create a glitchy audiovisual performance, using live coding, glitchy soundscapes, and synchronized glitch visuals to create an immersive and multisensory experience that combines music, visuals, and technology in a unique and innovative way.',
  'Apply a mosaic pixelation effect, using carefully placed mosaic tiles and gradual transitions to create a visually interesting and textured effect that adds depth and dimension to the artwork.',
  'Transform it into an abstract geometric design, using intricate patterns, harmonious color combinations, and precise geometrical shapes to create a visually captivating and aesthetically pleasing composition that explores the beauty of geometry and symmetry.',
  'Make it a futuristic concept spaceship design, using sleek lines, streamlined forms, and innovative technological features to create a visionary spacecraft that pushes the boundaries of imagination and possibilities.',
  'Give it a vintage film noir aesthetic, using film grain effect, noir lighting, and a black and white or desaturated color palette to evoke a sense of mystery, nostalgia, and cinematic atmosphere reminiscent of classic film noir movies.',
  'Create a kinetic wind sculpture, using dynamic forms, organic shapes, and responsive movement to harness the power and beauty of wind, creating an interactive and visually captivating artwork that changes with the flow of air.',
  'Apply a shattered mirror reflection effect, using shattered glass fragments, distorted reflections, and fragmented visual elements to create a visually striking and thought-provoking composition that challenges perceptions and explores themes of fragmentation and self-reflection.',
  'Transform it into a mixed media collage, using found objects, textured materials, and layered compositions to create a visually rich and textured artwork that combines different mediums and elements to create a multi-dimensional and tactile experience.',
  'Make it an abstract macro photography of textures, capturing the intricate details, patterns, and textures found in natural or everyday objects in a close-up perspective that reveals the hidden beauty and intricacies of the world around us.',
  'Give it a glitch art style, using glitchy animated elements, visual distortions, and dynamic glitch effects that respond to sound or music to create a visually and sonically immersive experience that challenges traditional notions of aesthetics and reality.',
  'Create a realistic still life painting with fruits and flowers, capturing their colors, textures, and forms with meticulous attention to detail and lifelike precision for a visually stunning and immersive representation of the natural world.',
  'Apply a surrealist photomontage technique, combining elements from different images to create unexpected and dreamlike compositions that challenge reality, provoke the imagination, and explore the subconscious mind.',
  'Transform it into a wireframe 3D model of an animal, highlighting its skeletal structure, form, and movement with wireframe rendering techniques for a unique and visually intriguing representation that combines art and technology.',
  'Make it a minimalist black and white architectural photograph, emphasizing clean lines, symmetry, and the interplay of light and shadows to showcase the beauty, simplicity, and elegance of architectural forms and structures.',
  'Give it a dreamy ethereal misty landscape effect, using soft lighting, diffused atmosphere, and subtle color tones to create a sense of tranquility, serenity, and mystery in the landscape, inviting the viewer to immerse themselves in the beauty of nature.',
  'Create a light installation with interactive projection mapping, using dynamic visuals, light effects, and interactive elements to transform the space, engage the audience, and create an immersive and interactive art experience that blurs the boundaries between art, technology, and reality.',
  'Transform it into a paper quilling sculpture of an animal, using meticulously rolled and shaped paper strips to create intricate and detailed representations of animals, showcasing the beauty of paper art and the skill of quilling craftsmanship.',
  'Give it a surreal floating cityscape composition at sunset, combining elements of architecture, landscape, and imagination to create a captivating and dreamlike cityscape that transports the viewer to a world of fantasy and wonder.',
  'Create an abstract video art projection, using generative visuals, abstract forms, and ambient soundscapes to create an immersive and multisensory audiovisual experience that stimulates the senses, evokes emotions, and invites contemplation and introspection.',
  'Apply a fragmented glitch effect, using pixel displacement, abstract patterns, and glitchy transitions to create a visually distorted and dynamic look that challenges traditional notions of perception, aesthetics, and visual representation.',
  'Transform it into a wire sculpture of a human figure, using wireframe elements to capture the grace, movement, and essence of the human form in a minimalist and abstract representation that explores the interplay of positive and negative space, light and shadow.',
  'Make it an abstract long exposure photography of city lights, using extended exposure times, intentional camera movement, and creative techniques to capture the energy, vibrancy, and rhythm of urban environments in a visually striking and evocative way that goes beyond literal representation.',
  'Give it a glitch art style, using abstract algorithmic patterns, chaotic visual elements, and digital glitches to create a visually arresting and thought-provoking artwork that challenges traditional notions of aesthetics, composition, and visual coherence.',
  'Create a hyperrealistic portrait in graphite pencil, using meticulous attention to detail, shading techniques, and texture rendering to capture the nuances and essence of the subject with lifelike precision and depth, creating a visually captivating and emotionally resonant representation.',
  'Apply a photorealistic digital painting technique, using advanced digital tools and techniques to recreate the subject with exceptional realism, attention to detail, and mastery of light, color, and texture for a truly lifelike and immersive representation that blurs the boundaries between digital art and reality.',
  'Transform it into a folded paper origami flower, using precise folds, delicate shaping, and intricate paper manipulation to create a visually stunning and intricate floral form that showcases the beauty, elegance, and craftsmanship of origami art.',
  'Make it a minimalist black and white portrait photograph, using simplicity, clean lines, and precise composition to capture the essence and personality of the subject in a timeless and impactful way that emphasizes their unique features and expressions.',
  'Give it a surreal floating island composition at sunrise, using dreamy colors, soft lighting, and imaginative elements to create a captivating and otherworldly scene that transports the viewer to a realm of imagination, wonder, and introspection.',
  'Create a glitchy audiovisual performance, using live coding, glitchy soundscapes, and synchronized glitch visuals to create an immersive and multisensory experience that combines music, sound, visuals, and technology in a unique and innovative way, engaging the audience in a dynamic and transformative artistic journey.',
  'Apply a mosaic pixelation effect, using carefully placed mosaic tiles, gradual transitions, and variations in scale and size to create a visually interesting and textured effect that adds depth, dimension, and visual interest to the artwork, inviting the viewer to explore the intricacies and patterns within the mosaic.',
  'Transform it into an abstract geometric design, using precise lines, intricate patterns, and harmonious color combinations to create a visually captivating and aesthetically pleasing composition that explores the beauty, symmetry, and mathematical perfection of geometric forms and structures.',
  'Make it a futuristic concept spaceship design, using sleek lines, innovative shapes, and advanced technological features to create a visionary spacecraft that pushes the boundaries of imagination, science, and possibility, inviting the viewer to envision a future of exploration, adventure, and discovery.',
  'Create a kinetic wind sculpture, using dynamic forms, organic shapes, and responsive movement to harness the power and beauty of wind, creating an interactive and visually captivating artwork that combines the elements of nature, motion, and sculpture to create a dynamic and ever-changing visual experience.',
  'Apply a shattered mirror reflection effect, using shattered glass fragments, distorted reflections, and fragmented visual elements to create a visually striking and thought-provoking composition that challenges perceptions, explores themes of fragmentation and self-reflection, and invites the viewer to question the nature of reality and identity.',
  'Transform it into a mixed media collage, using found objects, textured materials, and layered compositions to create a visually rich and textured artwork that combines different mediums, textures, and elements to create a multi-dimensional and tactile experience that invites the viewer to explore and discover new layers of meaning and symbolism within the artwork.',
  'Make it an abstract macro photography of textures, capturing the intricate details, patterns, and textures found in natural or everyday objects in a close-up perspective that reveals the hidden beauty, complexity, and diversity of the world around us, inviting the viewer to appreciate the beauty of the small and often overlooked details in the world.',
  'Give it a glitch art style, using glitchy animated elements, visual distortions, and dynamic glitch effects that respond to sound or music to create a visually and sonically immersive experience that challenges traditional notions of aesthetics, perception, and visual representation, inviting the viewer to question the boundaries between the digital and analog worlds and explore the aesthetics of glitches and errors in the digital realm.',
  'Create a realistic still life painting with fruits and flowers, capturing their colors, textures, and forms with meticulous attention to detail, skillful brushwork, and a deep understanding of light, shadow, and composition, creating a visually stunning and immersive representation that celebrates the beauty and fragility of the natural world.',
  'Apply a surrealist photomontage technique, combining elements from different images to create unexpected and dreamlike compositions that challenge reality, provoke the imagination, and explore the subconscious mind, inviting the viewer to dive into the depths of the subconscious and explore the hidden realms of the psyche.',
  'Transform it into a wireframe 3D model of an animal, using wireframe rendering techniques to emphasize the underlying structure, form, and movement of the animal, capturing its essence and energy in a minimalist and abstract representation that celebrates the beauty and grace of the animal kingdom.',
  'Make it a minimalist black and white architectural photograph, using simplicity, clean lines, and precise composition to highlight the architectural beauty, symmetry, and elegance of buildings and structures, inviting the viewer to contemplate the balance, harmony, and precision of architectural design.',
  'Give it a dreamy ethereal misty landscape effect, using soft lighting, diffused atmosphere, and subtle color tones to create a sense of tranquility, serenity, and mystery in the landscape, inviting the viewer to immerse themselves in the beauty of nature and experience a moment of peace and reflection.',
  'Create a light installation with interactive projection mapping, using dynamic visuals, light effects, and interactive elements to transform the space, engage the audience, and create an immersive and interactive art experience that blurs the boundaries between art, technology, and reality, inviting the viewer to become an active participant in the artwork and co-creator of the experience.',
  'Create an abstract video art projection, using generative visuals, abstract forms, and ambient soundscapes to create an immersive and multisensory audiovisual experience that stimulates the senses, evokes emotions, and invites contemplation and introspection, inviting the viewer to embark on a visual and sonic journey of exploration and self-discovery.',
  'Apply a fragmented glitch effect, using pixel displacement, abstract patterns, and glitchy transitions to create a visually distorted and dynamic look that challenges traditional notions of perception, aesthetics, and visual representation, inviting the viewer to question the boundaries between reality and digital manipulation and to explore the aesthetics of glitches and errors in the digital realm.',
  'Transform it into a wire sculpture of a human figure, using wireframe elements to capture the grace, movement, and essence of the human form in a minimalist and abstract representation that explores the interplay of positive and negative space, light and shadow, inviting the viewer to contemplate the complexity, fragility, and beauty of the human experience.',
  'Make it an abstract long exposure photography of city lights, using extended exposure times, intentional camera movement, and creative techniques to capture the energy, vibrancy, and rhythm of urban environments in a visually striking and evocative way that goes beyond literal representation, inviting the viewer to reflect on the dynamics and complexities of urban life and the ever-changing nature of cities.',
  'Give it a glitch art style, using abstract algorithmic patterns, chaotic visual elements, and digital glitches to create a visually arresting and thought-provoking artwork that challenges traditional notions of aesthetics, composition, and visual coherence, inviting the viewer to question the boundaries of art, technology, and perception and to explore the beauty of imperfection, randomness, and errors in the digital realm.',
  'Create a hyperrealistic portrait in graphite pencil, using meticulous attention to detail, shading techniques, and texture rendering to capture the nuances and essence of the subject with lifelike precision and depth, creating a visually captivating and emotionally resonant representation that invites the viewer to connect with the inner world and emotions of the subject.',
  'Apply a photorealistic digital painting technique, using advanced digital tools and techniques to recreate the subject with exceptional realism, attention to detail, and mastery of light, color, and texture for a truly lifelike and immersive representation that blurs the boundaries between digital art and reality, inviting the viewer to question the nature of perception and the power of artistic representation.',
]

export { generatePrompts }
